# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.18.4

# Mod Properties
mod_version=1.0.0
maven_group=com.bulkenchant
archives_base_name=bulkenchant

# Dependencies
fabric_version=0.136.1+1.21.8
